### PR TITLE
BEAST TOKEN

### PR DESCRIPTION
**Pull request by WorldLot**
BEAST TOKEN

Smart contract address:
0x4ea1771f6ae14dc51e5f3236afca5de34b2c8021

Token symbol: BEAST

Telegram group: https://t.me/TheCryptoExperiement
(You can see a great community here which believe in this project and are excited to start purchasing BEAST token in order to pay for the service I am going to provide,

Issuer's official website:

Created on minereum.com
can check on tokenservice.minereum.com

Description: 
  BEAST token is a utility token which has no ICO nor intial funding but is creating a premium crypto 
  analysis website where top analytics can review ICOs and cryptocurrencies, memebrs will pay a monthly fee with
the BEAST token and be able to upvote the top reviews. The most upvoted individual will receive a % in Ethereum of the total users. This is a revolutionary proect which is partially an experiment but is gathering the crypto community 

You can see our roadmap and updated visions on the official crypto beast website where this service will be implemented:
http://cryptobeast.uk/index.php/2018/07/03/beast-token-update

I have a FB group which is very behind this idea:
https://www.facebook.com/groups/cryptobeast.uk/
So there are potentially users from the start which will start purchasing BEAST on fork delta for my service.

My youtube channell:
https://www.youtube.com/cryptobeast

I want to thank you for your time and me and my community look forward to seeing BEAST token on FORK DELTA.

### CODE REVIEW

**Comment by freeatnet** [comment]
@WorldLot The error comes from you having description text at the root level, like so:
```yaml
description:
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec eleifend neque...
```

Simply indent it with 2 spaces like so:
```yaml
description:
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec eleifend neque...
```

**Comment by WorldLot** [comment]
We have updated our short whitepaper (three pager) 
You can see a copy of it on our website here:
http://cryptobeast.uk/wp-content/uploads/2018/09/THREE-PAGER.pdf

**Comment by therealMikkoK** [comment]
@freeatnet May I?

**Comment by WorldLot** [comment]
Hello
I have spoken to my advisor and my development team and have been advised that i should delay the token listing.
This is due to the development of the site being delayed, I wish to list my token and there be an influx of buy orders due to the the need for the token (for the membership fees.
Please advise me of how I can delay or if I should just update you when we wish to list the token.

**Comment by therealMikkoK** [comment]
@WorldLot 
Hello,
we can do it here.
Do you have a schedule you're working on?

**Comment by WorldLot** [comment]
So right now we wish to get the token on the platform ones we have a stable user flow to make sure the listing goes smoothly for both the exchange and ourselves. Unfortunately I don't have an exact time but it will be a month or two for sure. Will it be ok to keep this request open and message you on here once we have an exact date?

**Pull request closed without merging**
