### PR TITLE
0x289925d08b07e73dd0dd02d1407c877942215082

### PR DESCRIPTION
**Pull request by rartokens**
related to request issue#87 :  https://github.com/forkdelta/tokenbase/issues/87

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@raztoken Let's keep it to one Website. Which one do you prefer?

**Comment by raxtoken** [comment]
please use-  Website: http://rartokens.com/

**Comment by rartokens** [comment]
should I edit it or will you do the changes?

**Comment by JonathonDunford** [comment]
Needs to be 3 ticks.

**Pull request merged**
