### PR TITLE
CROM Token Listing

### PR DESCRIPTION
**Pull request by Cromhub**
Contract address: 0xff4385c58cc0aa2adb56e05b50fc9f7e7b213511

Issuer's official website: https://www.cromhub.com

Official contract address confirmation: https://www.cromhub.com/faq (Question No 6.)

A link to a third-party review or discussion of the token: 
https://coinidol.com/the-first-blockchain-based-platform-for-the-performance-marketing-advertising-industry-ico-announced/
https://btcmanager.com/crom-ico-streamlining-performance-marketing-system/
https://bitcoinexchangeguide.com/cromhub/
https://bitcointalk.org/index.php?topic=2333082.0

Description:
The CROM token is the token powering the CROMhub platform. It's the first-of-its-kind tracking and settlement platform for the performance advertising industry.
It is being developed by a team of highly-experienced veterans from the marketing industry. It is tailored to the exact needs of that industry, solving today‘s problems with a hands-on approach.

### CODE REVIEW

**Comment by tradedbytony** [comment]
This one has an open issue at #75

**Comment by JonathonDunford** [comment]
Address verified on cromhub.com: 0xff4385c58cc0aa2adb56e05b50fc9f7e7b213511

**Comment by JonathonDunford** [comment]
@Cromhub Is there a reason there hasn't been any activity on social medias or your Bitcointalk announcement since December, but you are requesting listing now?

**Comment by Cromhub** [comment]
@JonathonDunford we've spent last months working on potential business partnerships and, as announced last year and presented on the project timeline (available on our website), finalizing Q1 milestone and jumping with the team on development.

**Comment by 2smpl2** [comment]
Why is this closed? Is it possible to please get this added to ForkDelta?

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

**Comment by freeatnet** [comment]
@Kryptoniq https://www.cromhub.com/ is at "ICO has ended: CROM PROJECT WILL CONTINUE IN 2018", https://blog.cromhub.com/ hasn't been updated since Nov 18, 2017. Does this look dead to you?

**Comment by 2smpl2** [comment]
@freeatnet @Kryptoniq https://t.me/CROMhub is still alive. Please could we have this list so that I can exchange my tokens?

**Pull request closed without merging**
