### PR TITLE
Updated the contract details of LOVE Token

### PR DESCRIPTION
**Pull request by remedcu**
The old contract has been changed and new contracts have been deployed.

### CODE REVIEW

**Comment by freeatnet** [comment]
@remedcu Can you link the official contract change announcement, please?

**Comment by Kryptoniq** [comment]
@remedcu ping.

**Comment by remedcu** [comment]
We have updated our website: https://lovetoken.info

As well as in our official announcement thread: https://bitcointalk.org/index.php?topic=2942750.0

I talked about the same with freeatnet directly, so didn't replied here till now. Sorry.

**Comment by remedcu** [comment]
So, can you update the token details now?

**Comment by Kryptoniq** [comment]
Links provided does not contain any announcement of change of contract.

**Comment by remedcu** [comment]
I hope this will do: https://bitcointalk.org/index.php?topic=2942750.msg31416832#msg31416832

The website and the announcement thread contains the updated contract address.

**Comment by remedcu** [comment]
These are some of the places where we are listed:

https://icobay.net/icos/LOVE%20Token?is=active
https://www.trackico.io/ico/love-token/#team
https://www.list-ico.com/ico/love-token/
https://www.coinhills.com/ico/view/love-token/

**Comment by remedcu** [comment]
So, now is it possible or any other details do you require?

**Comment by remedcu** [comment]
I had to update the Bitcoin Talk Thread as that has been deleted as we announced the airdrop at the wrong board in Bitcoin Talk. If you have to check how long we have been here, please check our bounty thread for the same, as the new ANN Thread does not have any new messages yet.

I have listed some links above where our new token contract details have been listed, so I request you to update the token details as soon as possible.

Thank You

**Comment by JonathonDunford** [comment]
This address has been verified on the website: 0xb510788cbB9AEa54221D3DC8cCE2DfF629A1DBf7

**Comment by JonathonDunford** [comment]
@remedcu 

Is there some sort of official announcement about the website change and address change?

**Comment by remedcu** [comment]
@JonathonDunford 

We have attached a announcement thread of new contract here: https://bitcointalk.org/index.php?topic=3118263.msg32307679#msg32307679

**Comment by remedcu** [comment]
Etherscan has updated the details as well: https://etherscan.io/token/0xb510788cbb9aea54221d3dc8cce2dff629a1dbf7

**Comment by remedcu** [comment]
@tradedbytony 
Can you please change the label of this from "missing information" then, so that the update be done as soon as possible?

**Comment by JonathonDunford** [comment]
@remedcu 

This update should be live any minute now. :)

**Pull request merged**
