### PR TITLE
Add Lif token .yaml file

### PR DESCRIPTION
**Pull request by AugustoL**
ENS: lif.windingtree.eth
Website: windingtree.com
Token Address: 0xEB9951021698B42e4399f9cBb6267Aa35F82D59D
Verified Token contract on Etherscan: https://etherscan.io/token/0xeb9951021698b42e4399f9cbb6267aa35f82d59d
Decimals: 18
Symbol: LIF
Type: ERC20

### CODE REVIEW

**Comment by tradedbytony** [comment]
Same request as #485

**Comment by Kryptoniq** [comment]
#485

**Comment by AugustoL** [comment]
@Kryptoniq why did you closed it? this a PR and the other one is an issue.

**Comment by Kryptoniq** [comment]
Hi @AugustoL, only one is needed.

**Pull request closed without merging**
