### PR TITLE
Listing request: eosDAC

### PR DESCRIPTION
**Pull request by dali1986**

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@dali1986 

Can you provide:

- A link to the token issuer's official whitepaper.
- A link to an official page confirming the above contract address. This needs to be on the official domain of the token issuer. Etherscan does not count as a confirmation.
- A Bitcointalk announcement
- Some sort of third party verification of the project. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.

**Comment by dali1986** [comment]
Hi,

Thanks for the mail, we certainly appreciate the due diligence.

The website (http://www.eosdac.io) contains all of the information which we
would have put in the whitepaper.

The link to the token contract on the official website is on
https://eosdac.io/tokens/

The bitcointalk announcement is here -
https://bitcointalk.org/index.php?topic=3093391.0

Various other links are here: -

https://steemit.com/eos/@eosdac/introducing-eosdac-the-community-owned-eos-block-producer

https://www.reddit.com/r/eos/comments/821upo/eosdac_the_community_owned_eos_block_producer_75/

https://t.me/EOSDACio
https://twitter.com/eosdac
http://coinpriceprediction.com/social/eosdac-now-will-be-airdropping-to-exchange-wallets/

From a company perspective, eosDAC Ltd is a service provide to the DAC
based in Anguilla - Company Number 2468282 Spencer House, The Valley,
Anguilla, British West Indies. Blockmaker Ltd - also in Anguilla is also
providing services.

Best Regards,

Rob



---------- Forwarded message ----------

**Comment by dali1986** [comment]
Hi @dali1986

Just to add if you are looking for additional third party verifications 
Thomas Cox, VP or Product Development for Block One, Publisher of EOS.io 
software itself, makes numerous comments concerning his positive 
opinions on eosDAC, it's initiative and it's team on EOS telegram page:

https://t.me/eosdacio

EOS and eosDAC communities are most active on telegram channel.

Thomas Cox also further comments at our inception as Blockmaker:

https://steemit.com/eos/@blockmaker/blockmaker-io-core-principles-and-token-distribution-details

*thomasbcox(46)<https://steemit.com/@thomasbcox>* · last month 
<https://steemit.com/eos/@blockmaker/blockmaker-io-core-principles-and-token-distribution-details#@thomasbcox/re-blockmaker-blockmaker-io-core-principles-and-token-distribution-details-20180207t192124028z>

This is an extremely intriguing and exciting development. I will be 
following your work closely.

<https://steemit.com/eos/@blockmaker/blockmaker-io-core-principles-and-token-distribution-details#> 

$0.00
1 
vote<https://steemit.com/eos/@blockmaker/blockmaker-io-core-principles-and-token-distribution-details#> 


  *


Reply

and Luke Stokes, one of the 21 Steem Block Producer does the same here:

https://steemit.com/eos/@eosdac/introducing-eosdac-the-community-owned-eos-block-producer

If you require any further confirmation of our legality, I'd be happy 
provide you with further corporate information.

We are excited to work with forkdelta, given that we are a decentralized 
entity, we have chosen to work with decentralized exchanges for out 
token trading. We believe that there will be considerable demand for 
trading our token in the coming months, before and after the airdrop and 
before are after Block Producer elections on the EOS chain launch in 
early June.

With much appreciation,

Will Stephens

**Comment by dali1986** [comment]
Just following up on this - I just want to check if there is anything else we need to do,

Many thanks

Rob

**Comment by Kryptoniq** [comment]
https://hacked.com/ico-analysis-eosdac/

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x7e9e431a0b8c4d532c745b1043c7fa29a48d4fba, http://www.eosdac.io/

**Comment by freeatnet** [comment]
Thank you for your request! Your token will be listed on April 9th, 2018. You will receive a notification of this issue closing once the listing is added to the platform (keep in mind there may be a delay of up to 30 minutes between the listing being added and all users seeing it).

Once listed, the token will appear for all users of ForkDelta (token list, ticker) and will be tradeable at a pre-defined URL featuring your token symbol. We will also announce the listing on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Comment by dali1986** [comment]
Thanks Arsenly,

Is it allowed to put a few sell orders on the contract address prior to
official listing?

Regards,

Rob


---------- Forwarded message ----------

**Comment by freeatnet** [comment]
@dali1986 For sure.

**Comment by freeatnet** [comment]
Thank you for your request! OneRoot Network Token has been listed: https://forkdelta.github.io/#!/trade/RNT-ETH. We will announce the listing on our social channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by dali1986** [comment]
Hi,

Sure this is just a slight error - We asked for eosDAC to be listed not
OneRoot network.

Regards,

Rob

**Comment by freeatnet** [comment]
@dali1986 Whoops. Wires got crossed somewhere. Comment fixed.

**Comment by dali1986** [comment]
Thank You Arsenly, Very much appreciated.

**Pull request closed without merging**
