### PR TITLE
URGENT Update and rename 0x7f2176ceb16dcb648dc924eff617c3dc2befd30d.yaml to …

### PR DESCRIPTION
**Pull request by jamesohni**
…0x6f539a9456a5bcb6334a1a41207c3788f5825207.yaml

We have upgraded our contract and many users are buying the wrong token and we are having to give back ethereum.

Please update it as soon as possible.

### CODE REVIEW

**Comment by OhniOfficial** [comment]
This is legitimate.

**Comment by freeatnet** [comment]
You are trying to change the contract address for the token issued by ohni.io. You must provide confirmation of the address change located on or linked from ohni.io.

**Comment by jamesohni** [comment]
Give me an email and I will provide confirmation from the official ohni.io email.

**Comment by freeatnet** [comment]
@jamesohni Confirmation MUST be publicly accessible and MUST be on the official website.

**Comment by jamesohni** [comment]
As I previously stated, we no longer have access to the domain because our employee who managed it is no longer with us.

When you asked me the first time I did it but then the employee changed it back.

It shouldn't be one person deciding this, it should be a community vote just like GMT.

**Comment by jamesohni** [comment]
Why did you close this?

**Pull request closed without merging**
