### PR TITLE
Request to List HunterCoin Token (HTC)

### PR DESCRIPTION
**Pull request by HunterCoinToken**
Requesting HunterCoin Token for Listing

Contract address:  0x87c8d6da29c030aae4d8ecb77b2f488f529de1f5

Issuer's official website: https://huntercoin.000webhostapp.com/

Official contract address confirmation: https://huntercoin.000webhostapp.com/

A link to a third-party review or discussion of the token: https://medium.com/@htctoken/what-is-huntercoin-29bcb2930195

Description:
"HunterCoin token is an Ethereum-based ERC-20 Token that focuses on being a faster and cheaper currency"

### CODE REVIEW

**Comment by HunterCoinToken** [comment]
[0x87c8d6da29c030aae4d8ecb77b2f488f529de1f5.yaml](https://github.com/forkdelta/tokenbase/pull/426/files)
@freeatnet  @Kryptoniq

**Comment by JonathonDunford** [comment]
@HunterCoinToken 

That isn't "third party" as it was written by you.

Please provide:
- Some sort of third party verification of the project. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.
- A Bitcointalk announcement
- A link to your whitepaper

**Comment by Kryptoniq** [comment]
@JonathonDunford please have a look at #424

**Comment by JonathonDunford** [comment]
Closed.

Please read: #424

**Pull request closed without merging**
