### PR TITLE
0xe99a76d5fb19bc419d72f355050045fad88e060f

### PR DESCRIPTION
**Pull request by rartokens**
in relation to request#88 : https://github.com/forkdelta/tokenbase/issues/88

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@raztoken Let's keep it to one Website. Which one do you prefer?

**Comment by raxtoken** [comment]
please use-  Website: http://rartokens.com/

**Comment by rartokens** [comment]
should I edit it or you will do the changes?

**Comment by JonathonDunford** [comment]
@rartokens If you'd like to edit your 3 PRs that would make our job easier :)

**Comment by JonathonDunford** [comment]
Don't forget the doc start.
[2m1:1[0m       [33mwarning[0m  missing document start "---"  [2m(document-start)[0m

need "---" on the first line of all yaml docs.

**Comment by rartokens** [comment]
Hueston, (Jonathan, BigBrother)
we got a problem...?
I hope I did not messed-up

**Pull request merged**
