### PR TITLE
Add OTCBTC (OTB) Token

### PR DESCRIPTION
**Pull request by v1nc3ntlaw**
OTCBTC Token info:

- https://etherscan.io/token/0xa86a0da9d05d0771955df05b44ca120661af16de
- How to verify: https://otcbtc.com/uploads/otcbtc_token_contract_address.txt
- 549 holders
- 1187 transactions
- Website: https://otcbtc.com
- OTCBTC ICO Announcement: https://www.jianshu.com/p/56f07aa07945

### CODE REVIEW

**Comment by v1nc3ntlaw** [comment]
Shorten the description and provide a verify contract address link on PR. Also the announcement is in Chinese.

**Comment by JonathonDunford** [comment]
verified: 0xa86a0da9d05d0771955df05b44ca120661af16de

**Comment by JonathonDunford** [comment]
verified: 0xa86a0da9d05d0771955df05b44ca120661af16de

**Comment by freeatnet** [comment]
Better looking contract address verification: https://support.otcbtc.com/hc/zh-cn/articles/115003813171

**Comment by v1nc3ntlaw** [comment]
Awesome, thanks.

**Pull request merged**
