### PR TITLE
Remove HashRush token

### PR DESCRIPTION
**Pull request by indriks**

### CODE REVIEW

**Comment by freeatnet** [comment]
Why?

**Comment by indriks** [comment]
HashRush is going to upgrade it's smart contract and swapping old RC tokens to new one.

**Comment by freeatnet** [comment]
@indriks I see. Could you please link the official announcement from your request?

**Comment by indriks** [comment]
Please remove HashRush token as we are on second token sale.
Here is the announcement: https://medium.com/@Hash_Rush/join-the-rush-coin-token-sale-7805ba57c087
Here is the token sales page: https://hashrush.com/ico/

**Comment by therealMikkoK** [comment]
@freeatnet please see message above

**Comment by indriks** [comment]
Hey @therealMikkoK !
1.  SM has not changed in terms of functionality. SC bugs and issues fixed.
2. Old tokens will be replaced by new one with help of airdrop. (Details in whitepaper)
3. First token will be replaced by new one. Old ticker RC will be replaced with RUSH. This is second ICO
4. HALT trading. All RC token holders will receive RUSH tokens after ICO2 via Airdrop. Old RC will not be in use after that.

**Comment by therealMikkoK** [comment]
Hello @indriks Thank you for your reply, as there are a lot of moving parts, and I'm new to this I forgot to add all the questions the team here had. So if you don't mind;
 I still don't have an answer on whether they are locking the tokens or when the snapshot is supposed to happen or if/how they have notified their existing token holders of the change (looking at the post, it only talks of ICO, not token swap)

**Comment by indriks** [comment]
Hello @therealMikkoK! 
Our existing token holders are notified through Discord -https://discordapp.com/invite/m7QaVxk . If you check our WP the section 7.5 under token swap. The distribution to old RC holders will happen starting from October as you can see in this webpage: www.hashrush.com/ico

**Comment by therealMikkoK** [comment]
@freeatnet @bobbypaintsstuf
one more pair of eyes on this, I got no issue.

**Comment by therealMikkoK** [comment]
@freeatnet is this a go?

**Pull request merged**
