### PR TITLE
0x468d58d6a52249844a166d0ef045dbdd7ce0c751

### PR DESCRIPTION
**Pull request by raztoken**
add new new token -  RAX Token

### CODE REVIEW

**Comment by raztoken** [comment]
related to request issue#86 : 
https://github.com/forkdelta/tokenbase/issues/86

**Comment by JonathonDunford** [comment]
@raztoken Let's keep it to one Website. Which one do you prefer?

**Comment by raztoken** [comment]
please use-  Website: http://rartokens.com/

**Comment by raxtoken** [comment]
is that ok to have 1 failing check?

**Comment by JonathonDunford** [comment]
Nope. I commented on this in one of your other PRs.

You just forgot the doc start "---" on the first line.

**Comment by raztoken** [comment]
Ah tripple dash what is needed. 
Now I could see my changes on edit but the view still showing the old. Is this ok?

**Pull request merged**
