### PR TITLE
Listing CIPHS

### PR DESCRIPTION
**Pull request by ciphs**
Hi. Detail as requested.

Contract: https://etherscan.io/address/0xa4ff5ce0556f9ff0797ae525ec5ba9b723878a3e
Website: http://ciphs.org
CIPHS Code: Open Source at https://github.com/ciphs/cryptocurrency
Website Code: Open Source at https://github.com/ciphs/website

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@ciphs Almost there!

Can you change the filename to lowercase and the address to lowercase?
Also, if you have HTTPS on your site, consider using HTTPS in your link.

**Comment by JonathonDunford** [comment]
Yep! You can do a pull request to update information in the future.

I see the file name change, need the address name change to lower case as well in the file.

**Comment by JonathonDunford** [comment]
Awesome. Looks like one more error to fix.
Travis CI is erroring out on "trailing whitespace"
AKA you have extra whitespaces at the end of every line.

**Comment by ciphs** [comment]
ok moment.

**Comment by JonathonDunford** [comment]
Cheers.

**Comment by ciphs** [comment]
Many thanks for the great support.

**Pull request merged**
