### PR TITLE
List VLD token

### PR DESCRIPTION
**Pull request by svenstucki**
Hi, this is a request to list the VALID (VLD) token.

Contract address: 0x922ac473a3cc241fd3a0049ed14536452d58d73c
Official website: https://valid.global

For a description and other information, please have a look at the commit.

Official address confirmations:
- Blog: https://blog.valid.global/how-to-recognise-and-transfer-your-valid-tokens-f5fcea69ad59
- Twitter: https://twitter.com/valid_global/status/986321088903774208
- Facebook: https://www.facebook.com/valid.global/posts/959514257558568

All these social accounts are listed from the main website.

Third-party reviews and discussions of the project:
- Smith and Crown review: https://www.smithandcrown.com/sale/valid-blockchain-based-personal-data-management-digital-age/
- https://neonewstoday.com/general/valid-digital-identity-neo-id/
- https://hackernoon.com/identity-blockchain-and-you-17cb1cbf2b60

Please let me know if you require any further information or articles, etc.

### CODE REVIEW

**Comment by freeatnet** [comment]
Good third-party links, @svenstucki!

A couple more conventional crypto-space sources:
1. https://hacked.com/ico-review-valid/
2. https://bitcoinexchangeguide.com/valid-global/

**Comment by freeatnet** [comment]
Thanks for your request, we have verified that the information provided is complete and accurate. You will receive a notification a few days before the token is live.

**Comment by svenstucki** [comment]
Thank you @freeatnet, looking forward to it.

**Comment by freeatnet** [comment]
@svenstucki  Thank you for your request! Your token will be live on **Thursday, June 28th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Pull request closed without merging**
