### PR TITLE
Add SocialX (SOCX) Token

### PR DESCRIPTION
**Pull request by sapph1re**
Token: https://etherscan.io/token/0x587c549c4113127340ac0f5e996cab7a4f35bb49
Website: https://socialx.network/
SocialX is a decentralized social media platform allowing users to distribute content seamlessly and to get paid for their contribution to the network. Photos and videos app that will store your files in the decentralized network securely in a single platform. Built-in license management allows you to decide if you want to keep your photos private or if you want to sell photo rights to others in exchange for SOCX tokens. SocialX is a community-driven project developed with the user’s best interest at heart.
Official page confirming the contract address: https://medium.com/@socialx/socialx-ico-ended-ae3aff0f3495
Third party about the ICO: https://www.coinschedule.com/icos/e1851/socialx-ico.html

### CODE REVIEW

**Comment by sapph1re** [comment]
Travis says it doesn't like some trailing spaces. Not sure what it is about though. Tried to follow the described format. Maybe the multiline description is done wrong?

**Comment by Kryptoniq** [comment]
Please fix the commit https://travis-ci.org/forkdelta/tokenbase/builds/346356514.

**Comment by Kryptoniq** [comment]
@sapph1re Trailing space is all whitespace located at the end of a line, without any other characters following it.

**Comment by sapph1re** [comment]
@Kryptoniq Thanks, fixed!

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x587c549c4113127340ac0f5e996cab7a4f35bb49, https://socialx.network/

**Comment by freeatnet** [comment]
@sapph1re Thank you for your request! SocialX has been listed: https://forkdelta.github.io/#!/trade/SOCX-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Comment by sapph1re** [comment]
Thank you!

**Pull request merged**
