### PR TITLE
Add HINT token

### PR DESCRIPTION
**Pull request by hintcoin**

### CODE REVIEW

**Comment by freeatnet** [comment]
Please file a request using the form here: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md

**Comment by mak2014** [comment]
Hi @freeatnet We have raised the request and it is already approved. Please see here #944 Thanks once again.

**Comment by hintcoin** [comment]
Hi @freeatnet , Just in case if you need this from official @hintcoin account. Please check this token add request #944 to reconsider this pull request. Thanks heaps.

**Comment by mak2014** [comment]
Hi @freeatnet @Kryptoniq Not trying to be pushy here but could you please let us know when our token will be listed. We are planing to release our pre-alpha version product shortly so it is mandatory for us to be listed on the exchange. I appreciate your time. Looking forward to hear from you. Cheers

**Pull request closed without merging**
