### PR TITLE
Request Listing Vetra

### PR DESCRIPTION
**Pull request by VetraCommunity**
Contract address : https://etherscan.io/address/0x7dcdbd2c6548774d301811658ddcb0e75eca9881
Total Supply: 18.000.000
Symbol: VETRA
Token Decimals: 18

Issuer's official website: https://vetra.info
Whitepaper : https://vetra.info/Whitepaper_Vetra.pdf
Forum : https://vetracommunity.info/
Facebook : https://www.facebook.com/VetraCommunityInfo/
Twitter : https://twitter.com/VetraOfficial
Telegram Group : https://t.me/VetraCommunity

Official contract address confirmation: https://vetra.info/presale You Can See The Contract Address On Page Below In The How To Join Presale Tittle On Smartcontract tiitle you can see 0x7dcdbd2c6548774d301811658ddcb0e75eca9881 Address Of Smartcontract

A link to a third-party review or discussion of the token: https://bitcointalk.org/index.php?topic=3070452.0

Description : Crypto Payment Platform & The Trading Platform Token
Driven By Community

### CODE REVIEW

**Comment by VetraCommunity** [comment]
@freeatnet @Kryptoniq

**Comment by tradedbytony** [comment]
An open issue can be found at #438

**Comment by JonathonDunford** [comment]
@VetraCommunity 

Please reply to @Kryptoniq 's comments from the original thread here.

**Comment by freeatnet** [comment]
@VetraCommunity This issue has been automatically closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so.

**Pull request closed without merging**
