### PR TITLE
Listing Request: RefToken (REF)

### PR DESCRIPTION
**Pull request by alexanderanter**
Contract address: 0x89303500a7Abfb178B274FD89F2469C264951e1f
https://etherscan.io/token/0x89303500a7abfb178b274fd89f2469c264951e1f
Verified source code:
https://etherscan.io/address/0x89303500a7abfb178b274fd89f2469c264951e1f#code

Name: RefToken
Symbol: REF
Decimals: 8
Total Supply: 50 000 000
Website: https://reftoken.io
Protoype: https://demo.reftoken.com
Whitepaper: https://reftoken.io/uploads/reftoken-wp.pdf
Yellow Paper: https://reftoken.io/uploads/RefToken-Yellow-Paper.pdf
FB: https://www.facebook.com/RefToken/
Twitter: https://twitter.com/reftoken
Telegram: https://t.me/reftoken

### CODE REVIEW

**Comment by Kryptoniq** [comment]
https://bitcointalk.org/index.php?topic=2149439
https://icobench.com/ico/reftoken

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x89303500a7abfb178b274fd89f2469c264951e1f, https://reftoken.io

**Comment by alexanderanter** [comment]
Hi, when will REF be added to forkdelta? "next few days" was 28 days ago.

Our token address are readable on our website at https://reftoken.io/token/ and in our guides:
https://reftoken.io/send-ref-with-myetherwallet/

**Comment by freeatnet** [comment]
Thank you for your request! The token you requested will be live on **Wednesday, June 6th, 2018**. You will receive a notification of this issue closing once the token has been added to the platform (keep in mind there may be a delay of up to 30 minutes for the change to appear for all users).

Once live, the token will appear for all users of ForkDelta (token list, ticker) and will be tradable at a pre-defined URL featuring your token symbol. We will also announce it on our platforms: Reddit, Twitter, Telegram, and Discord.

Please let me know if you have any questions or concerns.

**Pull request closed without merging**
