### PR TITLE
Listing request - Engraved Coin (XEG)

### PR DESCRIPTION
**Pull request by engravedTech**

### CODE REVIEW

**Comment by Kryptoniq** [comment]
Contract address found on your website is 0xc4c09770dC5b44F11ecb3ab78DfE563d28F03392.
Kindly update it to the address provided on PR.

**Comment by engravedTech** [comment]
Done, thank you @Kryptoniq

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x85a7c57a4068280dd1166089a18acf35b4ba11e2, https://engraved.tech

**Comment by freeatnet** [comment]
@engravedTech Thank you for your request! Engraved Coin has been listed: https://forkdelta.github.io/#!/trade/XEG-ETH We'll be announcing it on our social media channels shortly.

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Pull request merged**
