### PR TITLE
COGNX listing request

### PR DESCRIPTION
**Pull request by cognx**
Contract address: 0x74fe5f01f6f82e6feddacad6c0f09cf6933c43de
Symbol: COGNX
Full Name: COGNX
Decimals: 18

Website: http://www.cognx.co.in
Whitepaper: http://www.cognx.co.in/doc/whitepaper.pdf
Description: CognX project use cutting edge cognitive technologies to predict how specific crypto currencies will perform in the near future

Link to confirm contract: http://www.cognx.co.in in the "TOKEN DETAILS" section

more in depth details:
medium: https://medium.com/@cognx
twitter: https://twitter.com/COGNX_COIN
telegram:https://t.me/cognx

Third-party comment(s) on the token: https://bitcointalk.org/index.php?topic=2437063.0

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@cognx 

Your official roadmap says listed on EtherDelta?
Is there a reason there hasn't been activity on any of your social media channels for over a month?

Address confirmed: 0x74fE5F01F6f82E6FeDdAcAd6C0f09cF6933c43de

**Comment by cognx** [comment]
>Your official roadmap says listed on EtherDelta?
Project started months before the etherdelta ownership change. Anyway thanks for reporting, we fix the timeline. 

>Is there a reason there hasn't been activity on any of your social media channels for over a month?
We used our social channel during the token distribution. In this couple of months we worked hard to close our timeline and we are close to give to our community the first video of our alpha release. Very soon will come back to our media channels.

CognX Team

**Comment by cognx** [comment]
@JonathonDunford 
have some updates?
Thx

CognX Team

**Comment by Kryptoniq** [comment]
Safe to close. No project update since April.

**Pull request closed without merging**
