### PR TITLE
Listing request: GINNI (GNI)

### PR DESCRIPTION
**Pull request by supadupa2**
GINNI Token from MinersAtWork

---
addr: '0x4dfd2a190ece60e12977942c858a70644e4b18dd'
decimals: 2
description: >-
  GINNI (GNI) is a token specialising in Mining and FASTcoin ATM technology
  
links:
- Website: http://www.minersatwork.com

name: GINNI
symbol: GNI

### CODE REVIEW

**Comment by Kryptoniq** [comment]
1. Fix the errors detected by Travis CI https://travis-ci.org/forkdelta/tokenbase/builds/346639688.
2. Provide an official link that verifies the contract address
3. Provide link to a third-party review or discussion of the token

**Comment by supadupa2** [comment]
done pls check

**Comment by JonathonDunford** [comment]
@supadupa2 

Please provide an official link that verifies your provided address.
Please provide a link to a third party review.

**Comment by supadupa2** [comment]
Link to official ico page: https://www.minersatwork.com/icopage.html
link to third party review:
https://icorating.com/analytics/basic/minersatwork-basic-review/
https://bitcoinexchangeguide.com/miners-at-work/
Other press coverage is at minersatwork.com's press page

**Comment by freeatnet** [comment]
@Kryptoniq bump.

**Comment by Kryptoniq** [comment]
Thanks for your request, we have verified that the information provided is accurate. We'll be listing the token in the next few days, you'll receive an update when we do.
0x4dfd2a190ece60e12977942c858a70644e4b18dd, https://minersatwork.com/

**Comment by freeatnet** [comment]
@supadupa2 Thank you for your request! GINNI has been listed: https://forkdelta.github.io/#!/trade/GNI-ETH

If you like our project, please consider [donating](https://forkdelta.github.io/about/#donate). Your donations keep the project running and are always appreciated.

**Pull request merged**
