### PR TITLE
Added LOVE Token to ForkDelta

### PR DESCRIPTION
**Pull request by remedcu**
LOVE TOKEN

Contract address : 0xe6eFd46EB6CDd73A7fe1e760Fa0c25a299755a4B
Symbol = LOVE
Name = LOVE Token
Decimals = 8

Website 1: https://lovetoken.gq/

Bitcointalk Announcement link: https://bitcointalk.org/index.php?topic=2942750
Bitcointalk Bounty link: https://bitcointalk.org/index.php?topic=2955807

Github: https://github.com/LoveTokenAirdrop

Telegram Channel: https://t.me/lovetokenchat
Twitter: https://twitter.com/lovetokencrypto

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@remedcu There appears to be some weird character encoding in your description. If you can fix that, it looks good to go.

**Comment by remedcu** [comment]
Please recheck, I have changed the font.

**Comment by JonathonDunford** [comment]
Can you properly indent the description or use the single line version?

**Comment by remedcu** [comment]
Added indent into description.

**Comment by JonathonDunford** [comment]
My apologies for not mentioning this earlier. Filename and address must be lowercase.

**Comment by remedcu** [comment]
Changed to lowercase.

**Comment by JonathonDunford** [comment]
Awesome. Looks like two more errors to fix.
Travis CI is erroring out on "trailing whitespace"
AKA you have extra whitespaces at the end of every line.

Also, you need a new line at the end of the file.

**Comment by remedcu** [comment]
Added newline at the end.

**Comment by remedcu** [comment]
Thank You

**Pull request merged**
