### PR TITLE
Add Ethernet Cash (ENC)

### PR DESCRIPTION
**Pull request by ethernetcash**
**Contract address:**  0x039f5050de4908f9b5ddf40a4f3aa3f329086387

**Smart contract information:** https://etherscan.io/token/0x039f5050de4908f9b5ddf40a4f3aa3f329086387

**Token name:** Ethernet Cash
**Token symbol:** ENC
**Token decimals:** 18

**Smart contract has verified:** https://etherscan.io/address/0x039f5050de4908f9b5ddf40a4f3aa3f329086387#code

**Issuer's official website:** https://ethernet.cash

**Official contract address confirmation:** https://ethernet.cash/index.php#tokenSale

**A link to a third-party review or discussion of the token:** https://bitcointalk.org/index.php?topic=4103552
**In Chinese:** https://bitcointalk.org/index.php?topic=4345758.0

**Discussion links:**

- https://bitcoinexchangeguide.com/ethernet-ico-enc-token/
- https://medium.com/@ethernetcash/enc-token-distribution-announcement-3325b1ff4361
- https://icoranker.com/ico/ethernet-cash
- https://bountyairdroptoken.com/ethernet-cash-enc/
- https://www.bestcoins.co/ico/ethernet-cash
- https://steemit.com/airdrop/@superhecht/3nqj1b-new-airdrop-free-coins-token-ethernet-enc-get-9-999-00-enc-for-simple-social-media-tasks-more-for-referrals

**White Papers :**  https://ethernet.cash/docs/Ethernet-Cash-(ENC)-White-Paper.pdf

**Logo (132x132):** https://ethernet.cash/images/Logo132x132.png

**Social media:**
Facebook: https://www.facebook.com/ethernetcash.official/
Twitter: https://twitter.com/ethernetcash
Telegram: https://t.me/ethernetcash
Medium: https://medium.com/@ethernetcash

**Description:**

While existing solutions offer to solve just one problem at a time, our team is up to build a secure, useful, & easy-to-use product based on private blockchain. It will include easy cryptocurrency payments integration, and even a digital arbitration system.

At the end, Our aims to integrate all companies, employees, and business assets into a unified blockchain ecosystem, which will make business truly efficient, transparent, and reliable.

### CODE REVIEW

**Comment by freeatnet** [comment]
Please make sure your request (description of this PR) follows the required format: https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE/add-a-new-token.md

**Comment by freeatnet** [comment]
Thank you for your request, @ethernetcash! We'll review it as soon as we can. In the meanwhile, here's what to expect:

- Please make sure your request follows the [required format](https://github.com/forkdelta/tokenbase/blob/master/.github/ISSUE_TEMPLATE/add-a-new-token.md) and that the information provided is complete and accurate. This will improve the speed of processing your request greatly.
- Keep an eye on this issue. We will post all follow-up and additional questions here.
- You will receive a notification once your request has been reviewed for completeness and accepted.
- You will receive another notification when the token you requested is about to be added, along with the date when it is added.

Please note:
- Adding a token to ForkDelta Tokenbase **is free**, we do not charge for this service. If you receive any messages asking for payment, do not respond to them.
- We will not send or accept email or direct messages related to token addition requests.

**Comment by ethernetcash** [comment]
Dear Forkdelta,

We are still waiting for your approval.

Thanks,
Ethernet Cash

**Comment by freeatnet** [comment]
https://bitcointalk.org/index.php?topic=4840556.0

**Pull request closed without merging**
