### PR TITLE
Add AUSCOIN COIN (AUSC)

### PR DESCRIPTION
**Pull request by nwilson1412**
Contract address: 0x59f1b6d0f5105cf025a3de58858a9363f4fef084

Issuer's official website: auscoin.io

Description:  AUSCOIN Group is dedicated at bringing AUSCOIN to the mainstream consumer market through the implementation of its world-first ATM network; and to establishing AUSCOIN as one of the leading cryptocurrencies, emulating the same success as Bitcoin and other cryptocurrencies.

Holding AUSCOIN allows for fee reduction on the ATM network, as well as the 1% of the ATM revenue to buy back AUSCOIN.

Official contract address confirmation: https://www.auscoin.io/static/assets/documentation/AUSCOIN_FAQs.pdf

Links to third-party reviews or discussion of the token, the project/product, or the token issuer: https://medium.com/@maFarrukh/auscoin-ico-review-8645fdd0814d

### CODE REVIEW

**Comment by nwilson1412** [comment]
ERC20 contract can be found in their FAQ on the website; https://www.auscoin.io/static/assets/documentation/AUSCOIN_FAQs.pdf

**Comment by freeatnet** [comment]
Thanks for contributing the listing file; however, we ask you follow [this template](https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE.md) in your request description.

**Comment by nwilson1412** [comment]
Thanks for the update @freeatnet 

That has now been updated.

**Comment by samkazzauscoin** [comment]
Hello. Is any further information required? I am happy to provide more.

**Comment by Kryptoniq** [comment]
The third-party reviews are well researched with proofs. 
I strongly advice we do not list this token.

More links:
https://www.linkedin.com/pulse/bitcoin-critical-analysis-auscoin-raymond-chen
https://amp.reddit.com/r/CryptoCurrency/comments/7t49g0/auscoin_stay_far_away_from_this_ico/
https://cryptocoin.com.au/analysis/ico-analysis-auscoin-token/
https://coinspectator.com/news/23862/psa-auscoin-is-a-blatant-scam

**Comment by McToastyCarajo** [comment]
Auscoin is obviously NOT a scam.
They have a working business model, I think close to 30 operation Bitcoin ATMs over Aus. The owner has made his own name and face public throughout the entire ICO and still today. It is an actual coin and I vouch for it. If it was a scam, the owner would be long gone and they wouldn't still be installing new ATMs continuing to grow the project.

**Comment by rossi7277** [comment]
I feel sorry for these guys. One negative article and it feels like 100’s follow. I have traded thin coin myself on token store and a member of the telegram group. They currently have Bitcoin ATMs deployed and in use. I am very interested in this coin and keen to see them suceed. Positive reviews will certainly come in time.

**Comment by FlippaCryp** [comment]
I have used Auscoin ATMS for several purchases and have used there hotline number to be guided through the process. Definitely not a scam, as I spoke to a representative from Auscoin who guided me through the prompts. I have now purchased the necessary 10,000 Auscoin tokens that allow me to take receive BTC/LTC through the Auscoin ATM network at a discounted rate.

I have also bought and sold Auscoin several times through other address trading websites.

**Comment by cramirez0207** [comment]
Hey guys, I am an Auscoin investor and member of the Auscoin Hodl Club.

Auscoin has been deploying bitcoin machines and currently is the largest bitcoin ATM network in Australia. 

Done a tour around Australia, currently has more than 25 machines up and running, this project is legit and has my 100% support as an investor :)

**Comment by FlippaCryp** [comment]
@freeatnet   @Kryptoniq 

As an investor into Auscoin I do wish you take these articles on face value, as these media outlets have also posted how BTC and other coins are scam/bubble/only used to purchase drugs from dark web. 

Please follow link to an unedited version of the 60 minutes interview.

https://www.youtube.com/watch?v=wlVJd2rfF60

**Comment by freeatnet** [comment]
Source of this wave of support is the AUSCOIN telegram group: https://t.me/auscoin/12372.

**To all commenters:** if you want to defend the project, post links to independent fact-checking of the project and independent third party reviews. Unsourced statements and personal opinions will not improve the project's standing.

**Comment by Kinpapis** [comment]
I can vouch for the integrity of the Auscoin team, I have used their ATM's a lot for myself and others for both depositing and withdrawing money, they've answered questions immediately. This project will continue to grow and develop, they have met all requirements in Australia for KYC and are a much-needed facility in the cryptocurrency space in Australia (and eventually overseas).

**Comment by nwilson1412** [comment]
Hi please close this PR, it seems even the director has abandoned the possibility of it getting listed as he has deleted his comments/account and previous duplicate PR, and no-one is able to verify that it isn't a scam other than anecdotal reasons from "investors". I thought I was trying to help out a community coin, but at this stage it's a lost cause..

**Comment by freeatnet** [comment]
_Sigh._

Thank you for your request nevertheless, @nwilson1412! If you see interesting projects in the future, don't hesitate to let us know.

**Pull request closed without merging**
