### PR TITLE
Add ERC20 Token

### PR DESCRIPTION
**Pull request by dranastos**
Please add the XBV Token to ForkDelta...

Thank you!

### CODE REVIEW

**Comment by dranastos** [comment]
XBV is a blockchain venture capital company that invests in companies that are prime candidates to bring onto the blockchain.
  The companies brought on will have smart contracts created and those smart contracts will require XBV to operate creating demand for 
  the XBV token.

**Comment by JonathonDunford** [comment]
You should change your official link to purchase on your website to ForkDelta!

XBV will be added in a commit I will be pushing soon. :)

**Comment by JonathonDunford** [comment]
Once #85 goes through, this token will be added to tokenbase (and subsequently ForkDelta).

**Comment by dranastos** [comment]
Ok great.. will change the link!



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by JonathonDunford** [comment]
Will be added to FD once https://github.com/forkdelta/forkdelta.github.io/pull/60 goes through.

**Comment by dranastos** [comment]
What will the link on forkdelta once it cmgoes through be?



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by JonathonDunford** [comment]
https://forkdelta.github.io/#!/trade/XBV-ETH

**Comment by dranastos** [comment]
Thank you and the link was changed to forkdelta!

________________________________

**Comment by JonathonDunford** [comment]
@dranastos 

Do you have links to a third party review or bitcointalk with public comments?

**Pull request closed without merging**
