### PR TITLE
Add ShadowLink🔒Token

### PR DESCRIPTION
**Pull request by PodCoin**

### CODE REVIEW

**Comment by JonathonDunford** [comment]
Do you have a website or anything verifying the contract address?

**Comment by PodCoin** [comment]
@JonathonDunford The official website has been added as a link and contains the contract address.

**Comment by JonathonDunford** [comment]
Verified: 0x877fb817d5de492d20ec3190a812f6430e8faeba

**Comment by JonathonDunford** [comment]
There is another expensive coin with the ticker LNK: https://coinmarketcap.com/currencies/link-platform/

Any chance you can change it to something like SLNK

We can even do full names.

**Comment by PodCoin** [comment]
@JonathonDunford Of course, just changed it, no problem.

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/pull/80

**Pull request merged**
