### PR TITLE
Requesting NEXT PAYMENT GOLDEN Token for Listing

### PR DESCRIPTION
**Pull request by febieki23**
Requesting NEXT PAYMENT GOLDEN Token for Listing

---
addr: '0xfc7b16a373c2ca3770a6c1b234852eeefdce892a'
decimals: 0
name: NEXT PAYMENT GOLDEN
symbol: NXO

description: >-
  NXO is multipurpose coin NXO is not just for coins for trading only, but for payments as well. 
We will load goods from the refreshments of some Famous Online Shop Sites, even those that are difficult to buy when not using a credit card. 
NXO will ease Payment with NXO without need Paypal or maybe card credit. 
NXO will choose The Best Seller On A Large site like Amazon,alibaba, and other. 
We will also load home products to be loaded and shipped to all over the world justone click cekout goods will be ready to be sent. 
links:
- Email: developers@nxo.store
- Telegram: https://t.me/joinchat/G9gGZ0SkZIGgagI6hHO6jw
- Twitter: https://twitter.com/nxosupport
- Website: https://nxo.store
- Whitepaper:  https://nxo.store/images/whitepaper/WhitePaper.pdf
- ANN : https://bitcointalk.org/index.php?topic=3091796.new#new
- Youtube: https://www.youtube.com/watch?v=lDGkYqvXOoc&feature=youtu.be

### CODE REVIEW

**Comment by tradedbytony** [comment]
Two opened issues can be found at #459 and #367

**Comment by febieki23** [comment]
So when we list

**Comment by JonathonDunford** [comment]
@febieki23 Quit spamming. Your other issues will be closed.

**Comment by JonathonDunford** [comment]
@febieki23 

Please provide some sort of third party verification of the project. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.

Notes:
- CMO doesn't have this company listed on is LinkedIn.
+ Team member images don't show up in a tineye search
+ Text doesn't seem to be plagiarized.

**Comment by freeatnet** [comment]
@febieki23 This issue has been automatically closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need.

**Pull request closed without merging**
