### PR TITLE
Request listing Ecocrypto

### PR DESCRIPTION
**Pull request by ecocrypto2018**
We have made great efforts in building a strong Ecocrypto community. Ecocrypto's topic on bitcointalk has made nearly 200 investors interested in sharing the information (https://bitcointalk.org/index.php?topic=3069112). In addition, ECO tokens have reached over 200 people and still on the rise.

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@ecocrypto2018 

Please provide:

- A link to your official whitepaper
- A link to an official page confirming the above contract address. This needs to be on the official domain of the token issuer. Etherscan does not count as a confirmation.
- Some sort of third party verification of the project. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.

**Comment by ecocrypto2018** [comment]
Dear.
- White paper link: https://drive.google.com/file/d/1x4vJjDW3VBrY7EZEZkUq6hw4a4GKzjgT/view
- Official page show smart contract address: https://ecocrypto.io
- Our's Ecocrypto ANN Topic at bitcoin talk: https://bitcointalk.org/index.php?topic=3069112
Some comments from high ranked user:
**lamongan12345:** hi dev, i was quite interested in this project. when you want to raise the living standards of the poor or the common people. so that not only makes big people bigger. but what about the future of this project, have you considered the obstacles, problems that hinder the growth of this project as well as how your strategy to make this project continue to grow and succeed
**pantherx12** : you have idea to create new web-bank.
but its cant help poor people in bad countries. it will another platform to invest much money. and you have good motivation, but more people don't have exit to ethernet.
.....
We are collaborating with Fundyourselfnow to promote this project. We would much appreciate if Forkdelta support us.

**Comment by ecocrypto2018** [comment]
As a result of our recent marketing efforts, 12,000 members have shown their great interest in Ecocrypto project and are following us on Telegram. 
[https://t.me/joinchat/AAAAAFIZi4HDO6_CFAhVZA](https://t.me/joinchat/AAAAAFIZi4HDO6_CFAhVZA)
We do hope to have the support from Forkdelta soon. Best regards

**Comment by ecocrypto2018** [comment]
+addr: '0x2af989200e9cd8d3404b5b40f5e2f896302d9aa5'
+decimals: 8
+description: >-
+  Ecocrypto was established as a financial institution and has sharpened the business to become a decentralized Open source credit and Big Data Bureau on blockchain. Ecocrypto provides Individuals and SMEs with short-term loans as the best solution for their financial problems. Ecocrypto uses innovative risk scoring implemented by artificial neural network. Ecocrypto utilizes the power of Blockchain Technology as a tool to create the next generation of money and finance.
+links:
+- Website: https://ecocrypto.io
+- Bitcointalk: https://bitcointalk.org/index.php?topic=3069112
+- Facebook: https://www.facebook.com/EcoCrypto/
+- Telegram: https://t.me/joinchat/AAAAAFIZi4HDO6_CFAhVZA
+- YouTube: https://www.youtube.com/channel/UCt67ZuES3mknk_LJaX10J2w?view_as=subscriber
+name: Ecocrypto
+symbol: ECO

**Pull request closed without merging**
