### PR TITLE
Add Pycoin

### PR DESCRIPTION
**Pull request by ProphetDaniel**
Add Pycoin to token base.

### CODE REVIEW

**Comment by ProphetDaniel** [comment]
@freeatnet , can you please hurry up your review? Thank you!

**Comment by Arvindsinc2** [comment]
Pycoin is a **_next generation project_** that has huge potential in the market. It is better than all the existing crypto currency in terms of **speed, performance, security and feasibility** . Pycoin enables more than **3 million python** developers to write smart contracts and decentralized apps in python.

**Comment by Kryptoniq** [comment]
Please refrain from spamming the PR.

**Comment by freeatnet** [comment]
@CohomologyLabs Abusive behaviour towards our contributors will not be tolerated.

**Comment by freeatnet** [comment]
Please file a request using the form here: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md

**Pull request closed without merging**
