### PR TITLE
0x3c63d4b0330a1ab969ff0f8b2ba227540a15b0ca.yaml

### PR DESCRIPTION
**Pull request by coda7777**
Span Coin 0x3c63d4b0330a1ab969ff0f8b2ba227540a15b0ca

### CODE REVIEW

**Comment by freeatnet** [comment]
@coda7777 Your request still needs to provide contract address confirmation, as mentioned in [the guide.](https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/)

**Comment by coda7777** [comment]
corrected info, small cap address

**Comment by coda7777** [comment]
Address have been added to home page footer.

**Comment by Kryptoniq** [comment]
Please provide link to a third-party review or discussion of the token.

**Comment by coda7777** [comment]
we are pre-launching still.

**Comment by JonathonDunford** [comment]
@coda7777 

Would you like to request this after you have launched the token and have a third party review?

**Comment by freeatnet** [comment]
This issue has been automatically closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need.

**Pull request closed without merging**
