### PR TITLE
Please list GramGold Token GGT

### PR DESCRIPTION
**Pull request by benign01**
Please can you list our token on forkdelta GramGold Token GGT We would be very grateful
GGT contract : https://etherscan.io/token/0x92d1dedb17626cad8a32a36083aec4f19325e474
1,000,000,000 tokens
website https://gramgold.net
whitepaper https://gramgold.net/whitepaper
Team https://gramgold.net/index.php/the-team
Bitcointalk https://bitcointalk.org/index.php?topic=2908503
LinkedIn https://www.linkedin.com/in/lionel-refson-5608b552/
YOUTUBE https://youtu.be/-7IGXUU3TCw
telegram Group https://t.me/gram_gold
Twitter https://twitter.com/birminghamgold
Bitcointalk https://bitcointalk.org/index.php?topic=2908503
Slack https://gramgoldtoken.slack.com/
Facebook https://www.facebook.com/gramgoldtoken/
Steemit https://steemit.com/ico/@bgc/gramgold-ico-14-02-108
Reddit https://redd.it/7wf99d
Youtube Intro Video https://youtu.be/-f6pHc4bKzg Reddit Again https://www.reddit.com/r/ico/comments/7wzxvq/announcing_the_gramgold_ggt_token/ https://www.reddit.com/r/icocrypto/comments/7x0ms6/announcing_the_gramgold_ico_18022018/ https://gramgold.net/ https://www.birminghamgoldcompany.co.uk Medium https://medium.com/@birminghamgold/announcing-the-gramgold-ggt-token-45357de8b45 https://www.facebook.com/groups/338181963354159/

### CODE REVIEW

**Comment by JonathonDunford** [comment]
This PR is super messed up with multiple file submissions. Any chance you could rebase and try again?

**Comment by benign01** [comment]
Sorry I am not a dev. Will this coin be listed? Are there tech issues with it?

**Comment by benign01** [comment]
https://www.gramgold.net/the-gramgold-token

**Comment by JonathonDunford** [comment]
Will address in the issue opened.

**Comment by benign01** [comment]
description for GGT is 
Using Blockchain technology to revolutionize The Gold market.....Globally  
GGT is not just an ERC20 token backed by Gold and a
Global Gold Asset Trading Plaform 
based on blockchain technology & cryptocurrency...
Its a Gold Exchange, a Gold Vault a Gold ATM and a Foundation
#

**Comment by JonathonDunford** [comment]
Please go to #81

**Pull request closed without merging**
