### PR TITLE
Add ARB Token list

### PR DESCRIPTION
**Pull request by ARBtoken**
Issue : https://github.com/forkdelta/tokenbase/issues/1096

### CODE REVIEW

**Comment by ARBtoken** [comment]
Issue: https://github.com/forkdelta/tokenbase/issues/954 to list the token

**Comment by ARBtoken** [comment]
@freeatnet so Issue #954 for ARB

**Comment by freeatnet** [comment]
@arbtoken stop spamming.

**Comment by ARBtoken** [comment]
@freeatnet i just wait your reply because you are closed my Issue #1096

**Pull request closed without merging**
