### PR TITLE
List SmellyCoin (SMELLY)

### PR DESCRIPTION
**Pull request by SmellyCoin**
SmellyCoin's purpose is to let others know that they smell.
Send to friends, wives, anybody that smells.
Satire Token with large following.

Contract address can be verified on https://smellycoin.com
or the Bitcointalk thread: https://bitcointalk.org/index.php?topic=2871113.0

### CODE REVIEW

**Comment by SmellyCoin** [comment]
.yaml file has been formatted correctly

**Comment by JonathonDunford** [comment]
Once #85 goes through, this token will be added to tokenbase (and subsequently ForkDelta).

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/pull/60

Will be added to FD once that gets approved.

**Comment by JonathonDunford** [comment]
https://forkdelta.github.io/#!/trade/SMELLY-ETH

**Pull request closed without merging**
