### PR TITLE
Create 0xa3114b268ff4327525fbc0dd5c48e0b4304d07b9.yaml

### PR DESCRIPTION
**Pull request by msdong**
Spectraaltoken Listing on ForkDelta Thx.
Regards
Andreas Stammer

### CODE REVIEW

**Comment by tradedbytony** [comment]
Open issue at #343

**Comment by JonathonDunford** [comment]
@msdong 

Please provide all information from #343 here and address @Kryptoniq 's concerns here.

**Comment by JonathonDunford** [comment]
Notes:
Decent activity in Telegram
Decent activity on Twitter

**Comment by JonathonDunford** [comment]
User just spammed the hell out of the repository.

Be careful with this one.

**Comment by msdong** [comment]
sry but your script has much error who has coded? rookie?

**Pull request closed without merging**
