### PR TITLE
Change of Contract Address for ROICOIN

### PR DESCRIPTION
**Pull request by officialroicoin**
ROICOIN contract address has been changed from [0xc9d40360cac0d5fd69e9ddc2e32d9b683bb51ad4] to [0xc3aef0036f5b146440775b2a1d5bf45fd8992741]

### CODE REVIEW

**Comment by freeatnet** [comment]
Please provide a link to an official page confirming change of contract address.

**Comment by officialroicoin** [comment]
official announcment link : 
https://www.roicoin.io/blog.html

**Comment by JonathonDunford** [comment]
New address verified: 0xc3aef0036F5B146440775b2A1D5Bf45Fd8992741

**Comment by officialroicoin** [comment]
Notice & New contract address verified. Please merge the pull request. Thank you.

**Comment by freeatnet** [comment]
@officialroicoin Change needs fixing as per https://travis-ci.org/forkdelta/tokenbase/builds/348174788

**Comment by officialroicoin** [comment]
Fixed. please merge.

**Comment by freeatnet** [comment]
Change deployed.

**Pull request merged**
