### PR TITLE
Token Listing: EBX

### PR DESCRIPTION
**Pull request by FlamesEBX**
Contract address: 0xba4725e435a287e28783886fcbcb339436a6ae66

Issuer's official website: etherbyte.co

Official contract address confirmation:
Contract Address on the website [Scroll Down] https://www.etherbyte.co/etherbyte-1

Whitepaper V0.1:
https://docs.wixstatic.com/ugd/4f0d88_637ed7928c2e4e05b0efa6a516344433.pdf

A link to a third-party review or discussion of the token:
[Announcement] https://bitcointalk.org/index.php?topic=2779774.msg28433866#msg28433866

Description:
Etherbyte will become the leading form of peer to peer payments in everyday life.

### CODE REVIEW

**Comment by JonathonDunford** [comment]
Address verified: 0xba4725e435a287e28783886fcbcb339436a6ae66

**Comment by tradedbytony** [comment]
Two different tokens have requested to have the EBX ticker (#533 and #439).

**Comment by JonathonDunford** [comment]
Please fix:
- Bitcointalk announcement has no comments/reviews
- Please provide some sort of third party verification of the project. This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.

**Comment by FlamesEBX** [comment]
We are working on the Bitcointalk Announcement to get comments from third party. This is what we have so far.
https://bitcointalk.org/index.php?topic=2779774.0

**Comment by Kryptoniq** [comment]
@FlamesEBX BTW, your original BCT post has insufficient information about the project.

**Comment by FlamesEBX** [comment]
@Kryptoniq Theres two BCT post on the first comment on this. One is from the airdrop and the second its about the team. You say theres insufficient information about the project but there is a lot. There is also a whitepaper and a roadmpap where we discuss about the project and goals for this year. Dont know what you mean by "insufficient information". Can you please check the BCT again and review the whitepaper and roadmap. Thank you.

**Pull request closed without merging**
