### PR TITLE
Request to list MRC MobileRechargez Coin

### PR DESCRIPTION
**Pull request by josepchu**
Import tokens listed on ForkDelta.

### CODE REVIEW

**Comment by josepchu** [comment]
Import tokens listed on ForkDelta.

**Comment by freeatnet** [comment]
@josepchu Sorry, are you trying to request a token listing?

**Comment by josepchu** [comment]
Yes, It is correct. I want to list MRC token. Please review it. Thanks

**Comment by Kryptoniq** [comment]
1. Invalid bitcointalk thread.
2. Make the contract address available on the website.

**Comment by josepchu** [comment]
@Kryptoniq 
Invalid bitcointalk thread ==> fixed link
Make the contract address available on the website ==> I put it on my homepage.

Please check it. Thanks and Regards

**Comment by josepchu** [comment]
@Kryptoniq 

Invalid bitcointalk thread ==> fixed link
Make the contract address available on the website ==> I put it on my homepage.

Please help me check it. Thanks and Regards

**Comment by JonathonDunford** [comment]
This address has been verified on the website: 0xcA6F6E8Be2fc32946D38A92F7452578A8170Ca97

**Comment by JonathonDunford** [comment]
@josepchu 

Do you have any third party reviews or verification of the project?

This can include, but is not limited to: comments from high ranked users in Bitcointalk, third party blogs, ICO ranking websites, established company partnerships, etc.

**Comment by josepchu** [comment]
@JonathonDunford 

Not yet right now but we are working on it. We airdrop the token not make ICO. You can read the contract https://etherscan.io/address/0xca6f6e8be2fc32946d38a92f7452578a8170ca97#code source code.

I hope you can make our token listing on forkdelta.

Thanks and Regards,

**Comment by freeatnet** [comment]
@josepchu Closing this because it is missing required information. Please open a new **issue** with required information if you would like to list your token.

**Pull request closed without merging**
