### PR TITLE
Updated contract address

### PR DESCRIPTION
**Pull request by tomaszbec**
New contract has been deployed to main network.

### CODE REVIEW

**Comment by JonathonDunford** [comment]
Where is the verification of this new address on an official website?

**Comment by freeatnet** [comment]
Contract address should match file address, so:
1. A separate file must be created for the new contract address, details must be copied in there.
2. The old file should be updated with [a notice](https://github.com/forkdelta/tokenbase#notice).

**Comment by followcoin1** [comment]
Also notice verified and accepted
Please merge

**Comment by JonathonDunford** [comment]
"A separate file must be created for the new contract address, details must be copied in there.
The old file should be updated with a notice.

Additionally, as @JonathonDunford said, a confirmation of the contract address must be provided."

**Comment by JonathonDunford** [comment]
Address verified: 0x0200412995f1bafef0d3f97c4e28ac2515ec1ece 
@freeatnet They have a guide for changing to the new token. I think it's safe to change the official listing without requiring support for an "old" token. The new tokens were 1:1.

@followcoin1 Please consider linking to ForkDelta and instructing users to use ForkDelta to trade. EtherDelta doesn't work anymore.

**Comment by mrmm** [comment]
dont you think there should be and announcement link, or any other details before changing the contract to keep track of every edit mad on the tokenbase.

**Comment by freeatnet** [comment]
@tomaszbec Can you confirm that you want the listing replaced without adding the old contract address?

**Comment by followcoin1** [comment]
Does it mean that you will use new contract address instead ?
0x0200412995f1bafef0d3f97c4e28ac2515ec1ece

**Comment by freeatnet** [comment]
@followcoin1 Yes.

**Comment by followcoin1** [comment]
ok, now it's correct
New address: 0x0200412995f1bafef0d3f97c4e28ac2515ec1ece

**Comment by freeatnet** [comment]
Change deployed.

**Pull request merged**
