### PR TITLE
List Zilliqa (ZIL) Token

### PR DESCRIPTION
**Pull request by freeatnet**
As requested in https://github.com/forkdelta/forkdelta.github.io/issues/48.

### CODE REVIEW

**Comment by freeatnet** [comment]
Thanks @LtRiven!

**Comment by phyzzle** [comment]
Why is your roadmap not Updated?

**Comment by LtRiven** [comment]
Answer from the team in Telegram about roadmap not being updated 

https://i.imgur.com/7KMxSDv.png

**Comment by freeatnet** [comment]
@phyzzle Whose roadmap?

**Pull request merged**
