### PR TITLE
Added Presearch (PRE) to tokens list.

### PR DESCRIPTION
**Pull request by jejopl**
Name: Presearch
Symbol: PRE
Contract address:  0x88a3e4f35d64aad41a6d4030ac9afe4356cb84fa

Description: Presearch is an open, decentralized search engine that rewards community members with Presearch Tokens for their usage, contribution to, and promotion of the platform.

Telegram: https://t.me/presearch
Twitter: https://twitter.com/TeamPresearch
Facebook: https://facebook.com/presearch.io

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@jejopl Do you have a link to some place on your official website that verifies that is the correct contract address?

**Comment by g33kr4m** [comment]
+1

**Comment by jejopl** [comment]
https://www.presearch.io/uploads/TokenWithdrawal.pdf - page number 7

**Comment by txtechs** [comment]
+1

**Comment by crypto-bovine** [comment]
+1

**Comment by JonathonDunford** [comment]
Address verified: 0x88a3e4f35d64aad41a6d4030ac9afe4356cb84fa

**Comment by JonathonDunford** [comment]
https://github.com/forkdelta/forkdelta.github.io/pull/80

**Pull request merged**
