### PR TITLE
Listing Wixlar (WIX)

### PR DESCRIPTION
**Pull request by wixlar**
Contract Address: 0x7ba19b7f7d106a9a1e0985397b94f38eee0b555e
https://etherscan.io/token/0x7ba19b7f7d106a9a1e0985397b94f38eee0b555e
Verified Source Code: https://etherscan.io/address/0x7ba19b7f7d106a9a1e0985397b94f38eee0b555e#code

Name: Wixlar
Token Symbol: WIX
Decimal: 2
Website1: https://wixlar.com
Website2 TV Channel Broadcasting: http://wixlar.tv

Description: Wixlar Digital Currency offers 12 Services to the public and its own Blockchain TV Broadcasting Channel 24/7

Other Links:
- Whitepaper: https://drive.google.com/file/d/11bxqmtOHbA_EhJHMukdDEYBXmcUAMPJJ/view?usp=sharing
- Telegram: https://t.me/wixlar
- Facebook: https://www.facebook.com/WixlarCoin/
- Twitter: https://twitter.com/WixlarCoin
- G+: https://plus.google.com/118332878140924733855
- Gbusiness: http://wixlar.business.site/
- YouTube: https://www.youtube.com/channel/UCSXtrAk0o64u95_hWQ8F-bw
- Medium: https://medium.com/@WixlarCoin
- Blog: https://wixlarcoin.blogspot.com
- Feed: https://wixlar.com/feed/ 
- Status: https://status.wixlar.com/ 
- Slack: https://wixlarcoin.slack.com/
- Reddit: https://www.reddit.com/user/wixlarcoin
- Pinterest: https://www.pinterest.com/WixlarCoin
- Tumblr: https://wixlarcoin.tumblr.com/
- Linkedin: https://www.linkedin.com/in/WixlarCoin/
- Gravatar: https://en.gravatar.com/wixlar
- Imgur: https://wixlar.imgur.com/
- Github: https://github.com/wixlar
- BitCoinTalk: https://bitcointalk.org/index.php?topic=3245093
- CryptoCurrencyTalk: https://cryptocurrencytalk.com/topic/101183-annairdropreferral-wixlar-coin-ico-icotv/ 

ICO reviews:

1. ICOholder https://icoholder.com/en/wixlar-20771
2. CryptoRated at at https://cryptorated.com/ico-listing/wixlar/
3. FoundICO at https://foundico.com/ico/wixlar.html
4. TrackICO at https://www.trackico.io/ico/wixlar/
5. FXEMPIRE at https://www.fxempire.com/crypto/ico/wixlar
6. ICOGLORY at https://www.icoglory.com/ico/wixlar
7. ICODrip at https://icodrip.com/ico/wixlar/
8. CryptoCurrencyTalk at https://cryptocurrencytalk.com/topic/101183-annairdropreferral-wixlar-coin-ico-icotv/
9. CoinDelite at https://coindelite.com/ico-details-wixlar
10. CoinHills at https://www.coinhills.com/ico/view/wixlar/
11. ICOschedule at https://icoschedule.co.kr/2018/04/06/wixlar-coin-ico/
12. FoxICO at https://foxico.io/project/wixlarcoinico
13. ICORanker at https://icoranker.com/ico/wixlar/
14. ICODaily at https://icodaily.net/ico/wixlar/
15. ICObuffer at https://icobuffer.com/projects/wixlar_coin_ico

### CODE REVIEW

**Comment by wixlar** [comment]
would you please explain more so we can understand exactly what is missing?
so we can do it asap.

**Comment by mhyytine** [comment]
The content of the pull request is wrong. It should only contain a single new file, 0x7ba19b7f7d106a9a1e0985397b94f38eee0b555e.yaml with content according to the request format https://raw.githubusercontent.com/forkdelta/tokenbase/master/.github/ISSUE_TEMPLATE.md

**Comment by mhyytine** [comment]
Token listing guide: https://www.reddit.com/r/ForkDelta/comments/7tntnz/how_to_get_an_erc20_token_listed_on_forkdelta/
For help, join the Discord chat: https://discord.gg/mMnRq7m

**Comment by mhyytine** [comment]
Study the guide and then list the token request as an issue on https://github.com/forkdelta/tokenbase/issues/new

**Comment by freeatnet** [comment]
Please file a request using the form here: https://github.com/forkdelta/tokenbase/issues/new?template=add-a-new-token.md

**Pull request closed without merging**
